name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
homepage: https://github.com/flutter/plugins/tree/master/packages/in_app_purchase
version: 0.5.1+2

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.1.1
  meta: ^1.2.2
  collection: ^1.14.13

dev_dependencies:
  build_runner: ^1.11.0
  json_serializable: ^3.5.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.15.7
  # integration_test:
  #   sdk: flutter
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.inapppurchase
        pluginClass: InAppPurchasePlugin
      ios:
        pluginClass: InAppPurchasePlugin

environment:
  sdk: ">=2.10.4 <2.12.0"
  flutter: ">=1.12.13+hotfix.5"
